services:
  mydev:
    image: madiator2011/better-launcher:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env # pass additional env-vars (hf_token, civitai token, ssh public-key) from ".env" file to container
    environment:
      - LOCAL_DEBUG=True # change app to localhost Urls and local Websockets (unsecured)
    volumes:
      - ${HOME}/Projects/Docker/madiator:/workspace:rw # # TODO: create the below folder before you run!
    ports:
      - 22:22     # SSH
      
      - 7222:7222 # main Flask app port better-launcher "App-Manager"
      - 8181:8181 # File-Browser
      - 7777:7777 # VSCode-Server

      - 3000:3000 # ComfyUI
      - 6006:6006 # Tensorboard (needed by kohya_ss)
      - 7862:7862 # Forge (aka Stable-Diffiusion-WebUI-Forge)
      - 7863:7863 # A1111 (aka Stable-Diffiusion-WebUI)
      - 7864:7864 # Kohya-ss (lutzapps - added new Kohya app with FLUX support)
