services:
  mydev:
    image: madiator2011/better-launcher:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m flask run --host 0.0.0.0 --port 7222"]
    
    ports:
      - 5678:5678 # (random) port for debuggy (adjust together in above "command")
      - 7222:7222 # main Flask app port better-launcher "App-Manager"
      ### NOTE: during debugging, "start.sh" does *not* run, and following apps are not available right now:
      # - 22:22     # SSH

      # - 8181:8181 # File-Browser
      # - 7777:7777 # VSCode-Server

      # - 3000:3000 # ComfyUI
      # - 6006:6006 # Tensorboard (needed by kohya_ss)
      # - 7862:7862 # Forge (aka Stable-Diffiusion-WebUI-Forge)
      # - 7863:7863 # A1111 (aka Stable-Diffiusion-WebUI)
      # - 7864:7864 # Kohya-ss (lutzapps - added new Kohya app with FLUX support)
    
    env_file:
      - .env # pass additional env-vars (hf_token, civitai token, ssh public-key) from ".env" file to container
    
    environment:
      - LOCAL_DEBUG=True # change app to localhost Urls and local Websockets (unsecured)
      # if you NOT want need this behaviour, then set `LOCAL_DEBUG=False` [default],
      # which is the same as NOT setting this ENV var at all.

      - PYTHONDONTWRITEBYTECODE=1
      # keep Python from generating .pyc files in the container
      # this should however be removed for production as it disables bytecode caching

      - FLASK_APP=app/app.py

      - FLASK_ENV=development # changed from "production" [default],
      # only needed when "LOCAL_DEBUG=True", otherwise this ENV var can be obmitted

      - GEVENT_SUPPORT=True # gevent monkey-patching is being used, enable gevent support in the debugger,
      # only needed when "LOCAL_DEBUG=True", otherwise this ENV var can be obmitted
      
      - GIT_PYTHON_TRACE=full # enables full logging for the GitPython code, used for cloning the apps,
      # bcomfy custom_nodes, and refreshing the apps via git fetch/merge = git pull

      #- "FLASK_DEBUG": "0"  # "1" allows debugging in Chrome, but then VSCode debugger not works, "0" is the [default], which is the same as NOT setting this ENV var at all
    volumes:
      - ./app:/app:rw
      - ${HOME}/Projects/Docker/madiator:/workspace:rw # TODO: create the below folder before you run!